### ISSUE TITLE
systemd integration

### ISSUE THREAD

**Issue by dimidd** [seuros/capistrano-puma#196]
Thanks for this great gem. I wonder what is the best way to integrate it systemd? More details here:
http://stackoverflow.com/questions/42192083/capistrano-and-systemd-integration

**Comment by tagliala** [comment]
Hi, I'm starting taking a look into this.

I've noticed that there is a [dedicated documentation file](https://github.com/puma/puma/commits/master/docs/systemd.md) on the puma repository which mentions [capistrano puma](https://github.com/puma/puma/blob/master/docs/systemd.md#capistrano3-puma)

I'm still having troubles in understand which is the best practice here, because it says that " capistrano3-puma uses pumactl for deployment restarts, outside of systemd." but also that "Therefore running Puma in cluster mode, where the master can restart workers, is highly recommended. "

So I suppose that there should be a way to

1. Use puma in cluster mode and restart it through systemd
2. Update capistrano-puma scripts accordingly

Any help would be hugely appreciated

**Comment by Onumis** [comment]
I'm up for something like this...
If this gem already allows to customize and upload an nginx config, it could very well allow to customize and upload an systemd config.

**Comment by tagliala** [comment]
btw, this should have been closed in version 5.0

Ref: https://github.com/seuros/capistrano-puma#systemd #300
