### ISSUE TITLE
Invoke "puma:restart" & "puma:start" twice causes errors of Capistrano 3.9.0

### ISSUE THREAD

**Issue by CoSNaYe** [seuros/capistrano-puma#255]
capistrano (3.9.0)
capistrano3-puma (3.1.1)
capistrano-bundler (1.2.0)
puma (3.10.0)

The deploy process executes `puma:restart` then `puma:start`, which causes Capistrano to raises an error: 

```
Capistrano tasks may only be invoked once.
Since task `puma:restart' was previously invoked, invoke("puma:restart") at ..../capistrano3-puma-3.1.1/lib/capistrano/tasks/puma.rake:96 will be skipped.
```

> If you really meant to run this task again, use invoke!("puma:restart")
> THIS BEHAVIOR MAY CHANGE IN A FUTURE VERSION OF CAPISTRANO. Please join the conversation here if this affects you.
> https://github.com/capistrano/capistrano/issues/1686

From the discussion of above link, Capistrano team decides to use `invoke!` to solve this problem.  Currently, I just modified both `invoke 'puma:start'` at tasks/puma.rake:71 and `invoke 'puma:restart'` at tasks/puma.rake:96 to use `invoke!`.  

It works, but not sure if this action is correct.
Thanks.

**Comment by dan-jensen** [comment]
I'm using the same gem versions noted in the original comment, and I'm running into a similar problem, except with a repeat call to `start`:
```
...
using conf file /var/www/webapp.com/shared/puma.rb
Skipping task `puma:start'.
Capistrano tasks may only be invoked once. Since task `puma:start' was previously invoked, invoke("puma:start") at /[my_local_app_path]/vendor/bundle/gems/capistrano3-puma-3.1.1/lib/capistrano/tasks/puma.rake:71 will be skipped.
If you really meant to run this task again, use invoke!("puma:start")
THIS BEHAVIOR MAY CHANGE IN A FUTURE VERSION OF CAPISTRANO. Please join the conversation here if this affects you.
https://github.com/capistrano/capistrano/issues/1686
```
It looks like there is a call to `start` Puma in the puma.rb config file (possibly through the call to `preload_app!`), then a second call in the puma.rake task.  It looks like the `capistrano-puma` gem orchestrates both of those calls.  My first assumption was that I had mis-configured something, such as to trigger repeat calls to `start`, but I can't figure out what that might be.  Any thoughts on why `start` is being called twice?

**Comment by dan-jensen** [comment]
I've resolved this message in my environment by rebooting my servers and manually stopping then starting the services.  It's not clear to me what that did, but it apparently jarred something loose.

**Comment by leoarnold** [comment]
**My observations:**

* Does not seem to occur with single host deployments
* Only seems to occur when Puma is **not** running prior to Capistrano deployment
* Does **not** occur when Puma is running on **all-but-one** hosts
* The warning does not occur when I comment out these lines:

https://github.com/seuros/capistrano-puma/blob/bcb4887c39559a803db174ee30ccf8ca991bc180/lib/capistrano/tasks/puma.rake#L69-L72

**My conjecture:**

Given two target hosts `primary` and `secondary` with Puma running on neither, Capistrano will first invoke `puma:restart` where `on roles (fetch(:puma_role))` will check both hosts *in parallel*

https://github.com/seuros/capistrano-puma/blob/bcb4887c39559a803db174ee30ccf8ca991bc180/lib/capistrano/tasks/puma.rake#L62-L75

Since Puma is not running on either host, Capistrano receives one `puma:start` invocation *per host*, yielding the warning in question.

The fact that we still arrive at the desired result stems from the fact that *any* invocation of `puma:start` will start Puma on all host, as we have an `on roles (fetch(:puma_role))` block again:

https://github.com/seuros/capistrano-puma/blob/bcb4887c39559a803db174ee30ccf8ca991bc180/lib/capistrano/tasks/puma.rake#L12-L32
