### ISSUE TITLE
systemd: Neither a valid executable name nor an absolute path error because of ExecStart

### ISSUE THREAD

**Issue by steverob** [seuros/capistrano-puma#313]
`Capistrano::Puma::Systemd` is generating a systemd file for Puma with the below `ExecStart` value which uses the `$HOME` env var:

`ExecStart=$HOME/.rbenv/bin/rbenv exec bundle exec puma -C /home/ubuntu/app/shared/puma.rb`

This is causing the following error: 

```
systemd/system/puma.service:9: Neither a valid executable name nor an absolute path: $HOME/.rbenv/bin/rbenv
service: Unit configuration has fatal error, unit will not be started.
```
Going through systemd's manpage, it does say we need to use an absolute path for `ExecStart`: (https://man7.org/linux/man-pages/man5/systemd.service.5.html)
```
For each of the specified commands, the first argument must be either an absolute path...
```
Systemd version: 

```
ubuntu@ip-172-31-86-176:/etc/systemd$ systemctl --version
systemd 245 (245.4-4ubuntu3.2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

Ubuntu version: `Linux ip-172-31-86-176 5.4.0-1029-aws #30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by m4c3** [comment]
Try putting `set :rbenv_custom_path, "/home/ubuntu/.rbenv"` into your _deploy.rb_

**Comment by ccastillop** [comment]
I changed `set :rbenv_prefix, "RBENV_ROOT=#{fetch(:rbenv_path)} RBENV_VERSION=#{fetch(:rbenv_ruby)} #{fetch(:rbenv_path)}/bin/rbenv exec"` to  set :rbenv_prefix, "#{fetch(:rbenv_path)}/bin/rbenv exec"

It seems adding ENV  to ExecStart just does not work

**Comment by seuros** [comment]
@ccastillop  It is possible to set env variables now with 5.0.3

**Comment by TalkingQuickly** [comment]
Fix for me on Ubuntu 20.04 was to use `Environment` in the unit file to set env vars rather than setting them inline in `ExecStart` e.g:

```
[Service]
Type=simple
User=deploy
WorkingDirectory=/home/deploy/apps/rsra_rails6_example_production/current
Environment=RBENV_ROOT=/usr/local/rbenv
Environment=RBENV_VERSION=3.0.0
ExecStart=/usr/local/rbenv/bin/rbenv exec bundle exec puma -C /home/deploy/apps/rsra_rails6_example_production/shared/puma.rb
```

**Comment by TalkingQuickly** [comment]
My solution above has a bunch of holes in it. Looked into it a bit further and in my case it's due to how the Capistrano rbenv plugin changes the return of `SSHKit.config.command_map[:bundle]` so that it includes environment variables at the start. I ended up with this definition; https://github.com/TalkingQuickly/rdra_rails6_example/blob/master/config/deploy/templates/puma.service.erb

It's not generalisable, e.g. it has some rbenv specific stuff in it including hard coding the rbenv path to the default ubuntu system install one. But may be useful as a starting point for others.

**Comment by chriswnl** [comment]
Adding
`append :puma_service_unit_env_vars, "RBENV_VERSION=#{fetch(:rbenv_ruby)}", "RBENV_ROOT=/home/deployer/.rbenv"`
fixed it for me.

**Comment by sagar-ranglani** [comment]
Still not working for me, I tried solutions provided by @chriswnl, @ccastillop and @m4c3.
Using `Capistrano 3.16.0`, `Puma 5.3.1` & `capistrano3-puma 5.0.3`

When I directly change ExeStart in the .service file, I can run Puma when I provide the full path.
I wish to do it using the `deploy.rb` file.

Any help will be appreciated. Thank you! :-)

**Comment by hoppergee** [comment]
> Still not working for me, I tried solutions provided by @chriswnl, @ccastillop and @m4c3.
> Using `Capistrano 3.16.0`, `Puma 5.3.1` & `capistrano3-puma 5.0.3`
> 
> When I directly change ExeStart in the .service file, I can run Puma when I provide the full path.
> I wish to do it using the `deploy.rb` file.
> 
> Any help will be appreciated. Thank you! :-)

You can fix this issue in `deploy.rb` file through something like this:

```
set :rbenv_custom_path, "/home/ubuntu/.rbenv"
```

**Comment by rizqirizqi** [comment]
I'm also stuck with a similar error. What if I use rvm instead of rbenv?

**Comment by rizqirizqi** [comment]
Hi, I finally solved my issue by modifying the systemd unit file `/etc/systemd/system/puma_rasylva-web_production.service` manually on my server. However, I think it's a temporary solution, it may be better if the template can generate a more precise accurate unit file.

GENERATED BY TEMPLATE (`lib/capistrano/templates/puma.service.erb`):
```
[Unit]
Description=Puma HTTP Server for rasylva-web (production)
After=network.target

[Service]
Type=simple
User=
WorkingDirectory=/home/rasylva/apps/rasylva-web/current
ExecStart=~/.rvm/bin/rvm 3.0.1 do bundle exec puma -C /home/rasylva/apps/rasylva-web/shared/puma.rb
ExecReload=/bin/kill -TSTP $MAINPID
StandardOutput=append:/home/rasylva/apps/rasylva-web/current/log/puma.error.log
StandardError=append:/home/rasylva/apps/rasylva-web/current/log/puma.access.log
Restart=always
RestartSec=1
SyslogIdentifier=puma

[Install]
WantedBy=multi-user.target
```

MODIFIED:
```
[Unit]
Description=Puma HTTP Server for rasylva-web (production)
After=network.target

[Service]
Type=simple
User=rasylva
Environment=RAILS_ENV=production PATH=/usr/local/bin:/home/rasylva/.rvm/rubies/ruby-3.0.1/bin:/home/rasylva/.nvm/versions/node/v14.17.0/bin
WorkingDirectory=/home/rasylva/apps/rasylva-web/current
ExecStart=/home/rasylva/apps/rasylva-web/current/sbin/puma -C /home/rasylva/apps/rasylva-web/shared/puma.rb /home/rasylva/apps/rasylva-web/current/config.ru > /home/rasylva/apps/rasylva-web/current/log/puma.access.log 2>/home/rasylva/apps/rasylva-web/current/log/puma.error.log
ExecReload=/bin/kill -TSTP $MAINPID
Restart=always
RestartSec=1
SyslogIdentifier=puma

[Install]
WantedBy=multi-user.target
```

Here are some notes of what makes it works and I think it may help others and improve capistrano-puma template:
1. I need to specify User manually because I don't specify puma_systemctl_user config (I just upgraded from the capistrano3-puma v3.1.1 and puma v3.11 to capistrano3-puma v5.0.4 and puma 5.3.0, and the previous config doesn't have puma_systemctl_user)
2. I need to add the rvm Environment so that it can run `ruby` command
3. I need to add nvm Environment so that it can run `node` related command
4. The config.ru file is needed, otherwise, it will show `ERROR: No application configured, nothing to run`
5. I cannot use StandardOutput and StandardError because my systemd version somehow doesn't recognize the `append` command, it shows an error: `Failed to parse output specifier, ignoring: append:/home/rasylva/apps/rasylva-web/current/log/puma.error.log`. The alternative way is using stdout and stderr redirection: `<THE_PUMA_COMMAND> > /home/rasylva/apps/rasylva-web/current/log/puma.access.log 2>/home/rasylva/apps/rasylva-web/current/log/puma.error.log`
6.

**Comment by pedromschmitt** [comment]
Thx to the @rizqirizqi I could fix the same problem using RVM too.

I just added the path to RVM instead of using the `~` to solve it. I didn't need to add environment or other things

In my case changing the `~/.rvm` to `/home/deploy` on line 9.

**Comment by virusman** [comment]
I don't manually editing the configs is the proper solution to this. Is there a way to fix it in the gem?

**Comment by askrynnikov** [comment]
Using `Ubuntu 20.04`, `Capistrano 3.17.0`, `Puma 5.6.4`, `capistrano3-puma 5.2.0`, `capistrano3-rbenv 2.2.0` 

First, as most followed the path of changing `config/deploy/templates/puma.service.erb` which was downloaded from here [lib/capistrano/templates/puma.service.erb](https://github.com/seuros/capistrano-puma/blob/e5d870fcc943abab62670f4a8efd2922e8333adf/lib/capistrano/templates/puma.service.erb)

but it turned out to be enough just to comment out the line
`# set :rbenv_prefix, "RBENV_ROOT=#{fetch(:rbenv_path)} RBENV_VERSION=#{fetch(:rbenv_ruby)} #{fetch(:rbenv_path)}/bin/rbenv exec"`
which was introduced on the recommendation of [capistrano/rbenv#usage](https://github.com/capistrano/rbenv#usage)

Nothing broke, everything works.

P.S. And I just deleted my `config/deploy/templates/puma.service.erb` file

**Comment by hennii** [comment]
Setting the `rbenv_prefix` in the `deploy.rb` fixed this for me:

`set :rbenv_prefix, "/home/username/.rbenv/bin/rbenv exec`

This gets rid of the env variables `RBENV_ROOT` and `RBENV_VERSION` that seem to break the `ExecStart` command on my Ubuntu 22.04 box. I'm a deploy noob so I dunno if this will cause other issues, but it seems to work.
