### ISSUE TITLE
Release 6.0.0

### ISSUE THREAD

**Issue by TeamNautilus** [seuros/capistrano-puma#371]
Hi,

I have a Rails **7.1.2** project, with Puma **5.6.5** and the _capistrano3-puma_ at **5.2.0**.
Now, I want to upgrade Puma to **6.4.2** but this involves a regression of _capistrano3-puma_ at **1.2.1**.
However, if I force _capistrano3-puma_ at **6.0.0.beta.1**, all is good.

So, the questions are:

- Is the version **6.0.0.beta.1** safe for production?

- When do you plan to release the **6.0.0** version?

Thanks
Team Nautilus

**Comment by salex** [comment]
I've  had some issues over the last year when I moved to 7.0.x then 7.1.x.

Just had another one today trying to deploying an app to a local server. Puma wouldn't restart. The app had not been updated since rails 7.0 about 2 years ago. This had to do with (I think!) the puma systemd plugin.

I fixed it by remembering that the  6.0.0.beta.1 won't be updated until  you move you puma version to **gem  puma, ~> 6.0.** 
I have it running on 3 production app without any problem.  My current puma version is puma (6.4.2)

There is not much action on the site - mainly because it fairly stable.

**Comment by daralbrecht** [comment]
Hey!

Just checking in on the capistrano-puma project and noticed it's been a bit since the last update. Are there any plans to keep things moving or merge the beta for 6.0.0? Really appreciate all the effort that goes into this and just curious about what's next. Thanks for all the awesome work!

**Comment by ccastillop** [comment]
Hello. 
I tested with Rails 7.1 and Puma 6.4.2, to be deployed with systemd on a Ubuntu server. 
I found that the template for creating the service evaluates Gemfile to find `sd_notify` gem
If not, the Type=simple notification is set. 

Reading further, This is because Puma itself has built-in support for systemd's notify protocol since version 5.1. 

Maybe a fix is needed on[ this line](https://github.com/seuros/capistrano-puma/blob/2cc11846540489edda10d83e026c9bea04e6fab1/lib/capistrano/puma.rb#L31) to verify if the puma version is greater than 5.1
